const quotes=["Small progress is still progress.","Study smart. Rest properly. Repeat.","You do not need to be perfect — just consistent.","One focused session is better than an hour of distractions.","Future you will thank you for starting today."];
let subjects=JSON.parse(localStorage.getItem('subjects')||'[]');

function saveSubjects(){localStorage.setItem('subjects',JSON.stringify(subjects));displaySubjects();updateDashboard();loadProgress();}
function newQuote(){const el=document.getElementById('quote');if(el)el.textContent=quotes[Math.floor(Math.random()*quotes.length)];}
function addSubject(){const subject=document.getElementById('subject')?.value.trim();const examDate=document.getElementById('examDate')?.value;const difficulty=document.getElementById('difficulty')?.value;if(!subject||!examDate){alert('Please enter a subject and exam date.');return}subjects.push({subject,examDate,difficulty});document.getElementById('subject').value='';saveSubjects();}
function deleteSubject(index){subjects.splice(index,1);saveSubjects();}
function editSubject(index){const current=subjects[index];const name=prompt('Edit subject name:',current.subject);if(name?.trim()){current.subject=name.trim();saveSubjects();}}
function displaySubjects(){const table=document.getElementById('tableBody');if(!table)return;table.innerHTML='';const empty=document.getElementById('plannerEmpty');if(empty)empty.style.display=subjects.length?'none':'block';subjects.forEach((item,index)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${escapeHTML(item.subject)}</strong></td><td>${item.examDate}</td><td><span class="difficulty ${item.difficulty.toLowerCase()}">${item.difficulty}</span></td><td><div class="row-actions"><button class="icon-btn" onclick="editSubject(${index})">✎</button><button class="icon-btn" onclick="deleteSubject(${index})">×</button></div></td>`;table.appendChild(tr)});}
function searchSubjects(){const term=(document.getElementById('search')?.value||'').toLowerCase();document.querySelectorAll('#tableBody tr').forEach(row=>row.style.display=row.innerText.toLowerCase().includes(term)?'':'none');}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

async function generateAIPlan(){const table=document.getElementById('aiTable');if(!table)return;if(!subjects.length){alert('Add subjects in the Planner first.');return}const btn=document.getElementById('generateBtn'),status=document.getElementById('aiStatus');btn.disabled=true;btn.textContent='✦ Generating...';status.textContent='Ollama is analysing your subjects and building the timetable...';try{const response=await fetch('/api/generate-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjects,studyHours:document.getElementById('studyHours').value,sessionLength:document.getElementById('sessionLength').value,examFocus:document.getElementById('examFocus').checked})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Generation failed');renderAIPlan(data);localStorage.setItem('aiPlan',JSON.stringify(data));status.textContent='✓ Timetable generated locally by Ollama.';}catch(error){status.textContent='⚠ '+error.message;}finally{btn.disabled=false;btn.textContent='✦ Generate AI timetable';}}
function renderAIPlan(plan){const table=document.getElementById('aiTable'),empty=document.getElementById('aiEmpty'),overview=document.getElementById('aiOverview'),tips=document.getElementById('aiTips');if(!table)return;table.innerHTML='';plan.sessions.forEach(s=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${escapeHTML(s.day)}</strong><br><span class="muted">${escapeHTML(s.date)}</span></td><td>${escapeHTML(s.subject)}</td><td>${escapeHTML(s.focus)}</td><td>${escapeHTML(s.duration)} min</td><td>${escapeHTML(s.reason)}</td>`;table.appendChild(tr)});empty.style.display=plan.sessions.length?'none':'block';overview.textContent=plan.overview;tips.innerHTML=plan.tips.map(t=>`<span class="tip">💡 ${escapeHTML(t)}</span>`).join('');}
function downloadPDF(){if(!window.jspdf){alert('PDF library is still loading. Try again.');return}const plan=JSON.parse(localStorage.getItem('aiPlan')||'null');if(!plan?.sessions?.length){alert('Generate an AI timetable first.');return}const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(18);doc.text('StudyPilot AI Revision Timetable',20,20);doc.setFontSize(10);let y=32;doc.text(plan.overview,20,y,{maxWidth:170});y+=16;plan.sessions.forEach(s=>{if(y>275){doc.addPage();y=20}doc.setFont(undefined,'bold');doc.text(`${s.day} - ${s.subject} (${s.duration} min)`,20,y);doc.setFont(undefined,'normal');y+=6;doc.text(`${s.focus} — ${s.reason}`,20,y,{maxWidth:170});y+=10});doc.save('StudyPilot-AI-Timetable.pdf');}

function loadProgress(){const canvas=document.getElementById('studyChart');if(!canvas||typeof Chart==='undefined')return;document.getElementById('subjectCount').textContent=subjects.length;const labels=subjects.map(s=>s.subject),data=subjects.map(s=>s.difficulty==='Hard'?3:s.difficulty==='Medium'?2:1);document.getElementById('sessionCount').textContent=data.reduce((a,b)=>a+b,0);if(window.studyChartInstance)window.studyChartInstance.destroy();window.studyChartInstance=new Chart(canvas,{type:'bar',data:{labels,datasets:[{label:'Recommended sessions',data}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});}
function updateDashboard(){const tasks=document.getElementById('tasks'),hours=document.getElementById('hours');if(tasks)tasks.textContent=subjects.length;const total=subjects.reduce((sum,s)=>sum+(s.difficulty==='Hard'?3:s.difficulty==='Medium'?2:1),0);if(hours)hours.textContent=Math.round(total*.75*10)/10;const streak=document.getElementById('streakCount');if(streak)streak.textContent=(localStorage.getItem('streak')||0)+' days';const badge=document.getElementById('badgeCount');if(badge){let n=subjects.length>=1?1:0;if(subjects.length>=5)n++;if(subjects.filter(s=>s.difficulty==='Hard').length>=3)n++;badge.textContent=n+' earned'}const bar=document.getElementById('progressBar'),label=document.getElementById('progressLabel');const progress=subjects.length?Math.min(100,subjects.length*12):0;if(bar)bar.style.width=progress+'%';if(label)label.textContent=progress+'%';const list=document.getElementById('upcomingExams');if(list){const upcoming=[...subjects].sort((a,b)=>a.examDate.localeCompare(b.examDate)).slice(0,4);list.innerHTML=upcoming.length?upcoming.map(s=>`<div class="exam-item"><div><strong>${escapeHTML(s.subject)}</strong><br><span>${escapeHTML(s.difficulty)} priority</span></div><span>${s.examDate}</span></div>`).join(''):'<p class="empty-state">Add a subject to see upcoming exams.</p>';}}

let timeLeft=1500,timerInterval=null;function updateTimer(){const el=document.getElementById('timer');if(!el)return;el.textContent=`${Math.floor(timeLeft/60)}:${String(timeLeft%60).padStart(2,'0')}`;}function startTimer(){playMusic();if(timerInterval)return;timerInterval=setInterval(()=>{if(timeLeft>0){timeLeft--;updateTimer()}else{clearInterval(timerInterval);timerInterval=null;localStorage.setItem('streak',Number(localStorage.getItem('streak')||0)+1);alert('🎉 Focus session complete! Take a short break.');updateDashboard()}},1000)}function resetTimer(){clearInterval(timerInterval);timerInterval=null;timeLeft=1500;updateTimer()}

function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light');updateThemeButton()}function updateThemeButton(){const btn=document.getElementById('themeBtn');if(btn)btn.textContent=document.body.classList.contains('dark')?'🌙':'☀️'}
const songs=[{name:'Rainy Lofi',file:'music/lofi1.mp3'},{name:'Chill Study Beats',file:'music/lofi2.mp3'},{name:'Night Coding Lofi',file:'music/lofi3.mp3'}];let currentSong=0;const audio=new Audio();audio.volume=.5;function playMusic(){if(!songs[currentSong])return;audio.src=songs[currentSong].file;audio.play().catch(()=>{});const el=document.getElementById('songName');if(el)el.textContent=songs[currentSong].name}function pauseMusic(){audio.pause()}function nextSong(){currentSong=(currentSong+1)%songs.length;playMusic()}audio.addEventListener('ended',nextSong);
function setCookieChoice(allowed){localStorage.setItem('cookieChoice',allowed?'allowed':'essential');document.getElementById('cookiePopup')?.classList.add('hidden')}
function init(){if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark');updateThemeButton();newQuote();displaySubjects();updateDashboard();loadProgress();updateTimer();const savedPlan=JSON.parse(localStorage.getItem('aiPlan')||'null');if(savedPlan)renderAIPlan(savedPlan);const cookie=document.getElementById('cookiePopup');if(cookie&&localStorage.getItem('cookieChoice'))cookie.classList.add('hidden');}
document.addEventListener('DOMContentLoaded',init);
